### ISSUE TITLE
Restore Branches

### ISSUE THREAD

**Issue by danny-hcs** [githubteacher/intro-oct-2015#87]
I noticed that after you delete a branch there is an option to restore it.  Is there a time limit on being able to restore a branch?

**Comment by githubteacher** [comment]
The `Restore branch` button should remain on the pull request as long as there isn’t another branch with the same name. There’s nothing in Git or GitHub that would block you from re-using an old branch name for new work — simple, short branch names like `bugfix` or `typo` get recycled often — but the `Restore` button won’t work if a new branch exists with the same name.
